export const MOUNTED_TODAY_WEATHER = "BB/weatherApi/MOUNTED_TODAY_WEATHER";

export const _GET_TODAY_WEATHER_REQUEST =
  "BB/weatherApi/_GET_TODAY_WEATHER_REQUEST";
export const _GET_TODAY_WEATHER_SUCCESS =
  "BB/weatherApi/_GET_TODAY_WEATHER_SUCCESS";
export const _GET_TODAY_WEATHER_FAILURE =
  "BB/weatherApi/_GET_TODAY_WEATHER_FAILURE";

export const MOUNTED_FORECAST_WEATHER =
  "BB/weatherApi/MOUNTED_FORECAST_WEATHER";

export const _GET_FORECAST_WEATHER_REQUEST =
  "BB/weatherApi/_GET_FORECAST_WEATHER_REQUEST";
export const _GET_FORECAST_WEATHER_SUCCESS =
  "BB/weatherApi/_GET_FORECAST_WEATHER_SUCCESS";
export const _GET_FORECAST_WEATHER_FAILURE =
  "BB/weatherApi/_GET_FORECAST_WEATHER_FAILURE";
