export const MOUNTED_SELECTED_CAMERAS =
  "BB/selectCamera/MOUNTED_SELECTED_CAMERAS";

export const _GET_SELECTED_CAMERAS_REQUEST =
  "BB/selectCamera/_GET_SELECTED_CAMERAS_REQUEST";
export const _GET_SELECTED_CAMERAS_SUCCESS =
  "BB/selectCamera/_GET_SELECTED_CAMERAS_SUCCESS";
export const _GET_SELECTED_CAMERAS_FAILURE =
  "BB/selectCamera/_GET_SELECTED_CAMERAS_FAILURE";

export const MOUNTED_MOVING_OBJECT = "BB/selectCamera/MOUNTED_MOVING_OBJECT";

export const _GET_MOVING_OBJECT_REQUEST =
  "BB/selectCamera/_GET_MOVING_OBJECT_REQUEST";
export const _GET_MOVING_OBJECT_SUCCESS =
  "BB/selectCamera/_GET_MOVING_OBJECT_SUCCESS";
export const _GET_MOVING_OBJECT_FAILURE =
  "BB/selectCamera/_GET_MOVING_OBJECT_FAILURE";
