export const MOUNTED_SELECTED_CAMERAS =
  "BB/selectCamera/MOUNTED_SELECTED_CAMERAS";

export const _GET_SELECTED_CAMERAS_REQUEST =
  "BB/selectCamera/_GET_SELECTED_CAMERAS_REQUEST";
export const _GET_SELECTED_CAMERAS_SUCCESS =
  "BB/selectCamera/_GET_SELECTED_CAMERAS_SUCCESS";
export const _GET_SELECTED_CAMERAS_FAILURE =
  "BB/selectCamera/_GET_SELECTED_CAMERAS_FAILURE";
